rocm-arch/rocm-arch

- rocm-dev/.SRCINFO
- rocm-dev/PKGBUILD
Fixes #49 
Relevant upstream discussion:
https://github.com/ROCm-Developer-Tools/rocprofiler/issues/18
> Remove rocprofiler from dependencies

- rocprofiler/.SRCINFO
- rocprofiler/PKGBUILD
The CMakeLists.txt of this projects suggests that rocprofiler only
depends on rocr-runtime:
set ( CPACK_DEBIAN_PACKAGE_DEPENDS "hsa-rocr-dev" )
The configuration error was caused by a wrong CMAKE_INSTALL_PREFIX
which should point to /opt/rocm, not /opt/rocm/rocprofiler.
> Fix rocprofiler package

- roctracer/.SRCINFO
- roctracer/PKGBUILD
* roctracer is a library and does not ship with an executable -> Delete
symlinks
* Fix CMAKE_PREFIX_INSTALL_PATH which should not include roctracer
* Convert python2 scripts to python3 code via 2to3
> Fix roctracer

- rocm-smi/.SRCINFO
- rocm-smi/PKGBUILD
- rocm-smi/python2_fix.patch
Running `rocm-smi` throws a lot of syntax warnings related to invalid usage of Python (`is` instead of `==` with strings). Also, the current patch is outdated and was already applied to upstream.
> Update python2 fix on rocm-smi to cover more warnings

- hip-hcc/.SRCINFO
- hip-hcc/PKGBUILD
This fixes issue #68 for `hip-hcc`
> [hip-hcc] Add missing python build dependency

- hsa-ext-rocr/PKGBUILD
It has the same version problem of #82 but this time I bumped the version. Let me know what will stick so I fix the other package. Also fixes permissions on folders (AMD insists on making folders group-writable for some reason)
> Bring hsa-ext-rocr up to the standard

- rocm-cmake/.SRCINFO
- rocm-cmake/PKGBUILD
No need to create temporary dirs for such a basic package :) also use single quotes where no substitution is performed and improve description.
> Cleanup rocm-cmake

- hsa-rocr/.SRCINFO
- hsa-rocr/PKGBUILD
This PR fixes #92 
The warnings
LoadLib(libhsa-ext-finalize64.so.1) failed: libhsa-ext-finalize64.so.1: cannot open shared object file: No such file or directory
are only visible in debug builds, see https://github.com/RadeonOpenCompute/ROCR-Runtime/issues/89.
Adding "-DCMAKE_BUILD_TYPE=Release" fixes this issue.
> [hsa-rocr] Release build to suppress warnings

- comgr/.SRCINFO
- comgr/PKGBUILD
- llvm-amdgpu/.SRCINFO
- llvm-amdgpu/PKGBUILD
- rocm-opencl-runtime/.SRCINFO
- rocm-opencl-runtime/PKGBUILD
In order to have a working PyTorch, LLVM_DYLIB has to turn off (as by default and in AMD packages). If it is compiled and used for links, PyTorch would fail with:
```
:CommandLine Error: Option 'disable-symbolication' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
```
Moreover, this allows llvm-amdgpu to be used only to compile Comgr as describe by ROC team (llvm-amd is just a patched version of llvm and should not be necessary in the future).
This PR includes modification for llvm-amdgpu, comgr and also rocm-opencl-runtime which does not need custom llvm (maybe just the official one).
> Llvm-amdgpu static

- hcc/.SRCINFO
- hcc/PKGBUILD
- hip-hcc/.SRCINFO
- hip-hcc/PKGBUILD
- hip/.SRCINFO
- hip/PKGBUILD
- miopen/.SRCINFO
- miopen/PKGBUILD
- rocblas/.SRCINFO
- rocblas/PKGBUILD
This PR includes what is needed to build MIOpen 3.3.0.
In order to update miopen to 3.3.0, rocblas should be build with tensile on (it is by default), see  https://github.com/ROCmSoftwarePlatform/rocBLAS/issues/991. Moreover, a CMAKE option should be add to workaround an update of boost.
To build rocblas with tensile, we need symlinks for extractkernel & hipconfig in PATH directory and a micro-patch for rocblas.
BTW, it seems that tensile need a lot of ram (or swap actually) to build all "kernels".
> Update miopen to 3.3.0

- rccl/.SRCINFO
- rccl/PKGBUILD
- rocthrust/.SRCINFO
- rocthrust/PKGBUILD
In order to build PyTorch, I had to add some symlink in /opt/rocm/include. It seems to be done for each subproject in ubuntu packages so maybe it should be done for other sub-projects.
> add symlink in /opt/rocm/include for sub-project

- hip-hcc/.SRCINFO
- hip-hcc/PKGBUILD
- hip/.SRCINFO
- hip/PKGBUILD
Fix a stupid typo for both hip and hip-hcc where hipconfig was written as hip-config.
> hip/hip-hcc: fix typo hip-config -> hipconfig

- hcc-git/.SRCINFO
- hcc-git/PKGBUILD
- hcc/.SRCINFO
- hcc/PKGBUILD
The package description for HCC is too long which breaks the syntax highlighting in vim.
> [hcc] Fix package description and remove CMAKE_BUILD_TYPE

- rock-dkms-firmware-bin/.SRCINFO
- rock-dkms-firmware-bin/PKGBUILD
ROCk-dkms split firmware into a different package. I can only find this binary release, but I guess that typical with firmware.
This is just a simple modification from the rock-dkms-bin package.
This package installs fine, but rock-dkms-bin doesn't on neither "5.6.15-1" or "4.19.125-1" (Manjaro), complaining about the missing `DRM_VER`.
P.S. I think the ROCk firmware is necessary for device support for OpenCL 2.2, but I'm not sure.
> [rock-dkms-firmware-bin] New package from 3.5

- atmi/.SRCINFO
- atmi/PKGBUILD
Shorten package description, update dependencies, add option ROCM_VERSION to `cmake`. Otherwise the package does not build. Install MIT license file. The package now builds successfully in a clean chroot.
> [atmi] Update dependencies, builds in clean chroot

- hipsparse/.SRCINFO
- hipsparse/PKGBUILD
Resolves #207 
Currently does not build. Relevant  [upstream issue](https://github.com/ROCmSoftwarePlatform/hipSPARSE/issues/121).
> [hipsparse] Update to 3.5.0

- rock-dkms-bin/.SRCINFO
- rock-dkms-bin/PKGBUILD
`DRM_VER` will only be defined for a hardcoded selection of OS names. Arch (and Manjaro) is not in that list, so the dkms compilation will fail.
This change patches the makefile to provide a default, which assumes same conditions as under some other OS names. That condition being that `$(kdir)` is defined and that it contains a Makefile with `VERSION` and `PATCHLEVEL`
This compiles successfully with 4.19 and 5.6 but not 5.7
(Because [pci_platform_rom was removed in 5.7](https://github.com/torvalds/linux/commit/86845e37aca4c80eace290a727a49caa8390febb) )
5.6 boots normally with the module installed, but I'm not sure how to check if it was actually loaded, or if it's still using the one in the kernel?
P.S. Unfortunately clinfo still reports opencl 2.0 (with rocm-opencl-runtime) so, unless …
> [rock-dkms-bin] Fix DRM_VER in dkms Makefile

- hsa-ext-rocr/.SRCINFO
- hsa-ext-rocr/PKGBUILD
Got a 404 file not found and found only the deb package for version 3.5.1
ps. Forgot to update .SRCINFO, sorry -_-
pps. Fixed now
> [hsa-ext-rocr] 404 on deb file and update to 3.5.1

- miopen-hip/.SRCINFO
- miopen-hip/PKGBUILD
Partially addresses #271 
To compile `miopen-hip` you need to use `hipcc`, i.e. `clang` from `amdgpu-llvm`. I can successfully compile the package but cannot pass all tests. Those that are related to rocBLAS fail at the moment. Could please someone else check this? Maybe @acxz ? I also had to disable the use of intrinsics in the `half` package and manually specify the path to the `clang`-internal header files.
> [miopen-hip] Change compiler to hipcc, add check() function

- hip-rocclr/.SRCINFO
- hip-rocclr/PKGBUILD
This is part of a fix for #271.
This PR adds a symlink for the include path `/opt/rocm/hip/include` to `/opt/rocm/include` so that `miopen-hip` can find the HIP header files.
> [hip-rocclr] Symlink include path to /opt/rocm/include

- miopen-hip/.SRCINFO
- miopen-hip/PKGBUILD
Fixes #271 
This PR needs the updated HIP package from #281 
Additionally add `clang` (for `clang-tidy`) and `rocminfo` as build depends.
> [miopen-hip] Successfull build in clean chroot

- rock-dkms-bin/.SRCINFO
- rock-dkms-bin/PKGBUILD
Regarding issue #267 ( and #269 )
I've not had time to test this in depth, but it seems to work on 5.6 and 5.7.0
However, not on 5.7.8 ( a header, `dt-bindings/leds/common.h` is missing during dkms build )
> [rock-dkms-bin] Update patch for #267

- rocclr/.SRCINFO
- rocclr/PKGBUILD
The default behavior of `cmake` seems to have changed with version 3.18 such that ROCclr's `CMakeLists.txt` does not work anymore. The patch is submitted as an upstream PR [here](https://github.com/ROCm-Developer-Tools/ROCclr/pull/16). The relevant issue is https://github.com/ROCm-Developer-Tools/ROCclr/issues/15
> [rocclr] Fix OpenCL includes

- rock-dkms-bin/.SRCINFO
- rock-dkms-bin/PKGBUILD
The build for `rock-dkms-bin` fails for the checksum on `rock_compatibility.patch`. Looking at the PKGBUILD, it pulls directly from the [repo pull request](https://github.com/RadeonOpenCompute/ROCK-Kernel-Driver/pull/95). This request was updated 16 hours ago, and the patch checksum no longer matches. 
```
==> Making package: rock-dkms-bin 3.5.1-2 (Fri 14 Aug 2020 09:45:52 PM MDT)
==> Retrieving sources...
-> Downloading rock-dkms-bin-3.5.1.tar.gz...
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100 5365k  100 5365k    0     0  5975k      0 --:--:-- --:--:-- --:--:-- 5968k
-> Downloading rock_compatibility.patch...
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total …
```
> [rock-dkms-bin] Patch file updated, build fails

- hip-rocclr/.SRCINFO
- hip-rocclr/PKGBUILD
Resolves #387
Some header files weren't found because one of ROCclr's cmake files referenced a file in the build dir instead of `/opt/rocm`.
> [hip-rocclr] Build in clean chroot

- hip-rocclr/.SRCINFO
- hip-rocclr/PKGBUILD
Remove `VERBOSE=1` from the `make -C build` line I used for debugging.
> [hip-rocclr] Remove verbosity flag from make

- README.md
~~Many issues seem to originate from `yay`'s caching. That's why I removed it from our README~~.
We agreed on explicitly mentioning `yay`.
I would like to hear @acxz's opinion on this before we merge it.
> Remove yay from readme, remove outdated warning

- miopen-hip/.SRCINFO
- miopen-hip/PKGBUILD
What is this about?
===================
First of all, it fixes https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/issues/1110
It would seem miopen's  CMake logic currently only looks for `clang-offload-bundler`, if `MIOPEN_HIP_COMPILER`
is clang++. If undefined, it falls back to `hipcc`, which results in `extractkernel` being used.
Upstream _miopen_ is built with `clang-offload-bundler` support, according to
`/opt/rocm-3.7.0/miopen/include/miopen/config.h` in the official docker container.
With this change in place, the config headers are essentially the same:
```patch
--- build/include/miopen/config.h	2020-09-12 00:01:00.140410402 +0200
+++ upstream/include/miopen/config.h	2020-09-11 23:34:40.735846511 +0200
@@ -49,7 +49,7 @@
// clang-format off
#define HIP_PACKAGE_VERSION_MAJOR …
```
> [miopen-hip] Make sure clang-offload-bundler is used

- hip-rocclr/.SRCINFO
- hip-rocclr/PKGBUILD
Resolves #426
Update package to new release and add rocminfo as a dependency to fix warnings of unitialized perl variables in the hipcc script.
> [hip-rocclr] Update to 3.8.0

- roctracer/.SRCINFO
- roctracer/PKGBUILD
- roctracer/deprecated_string_split.patch
Resolves #433 
The problem of deprecated python functions is already fixed upstream but is not included in the 3.8.0 release.
> [roctracer] Update to 3.8.0

- rocm-opencl-runtime/.SRCINFO
- rocm-opencl-runtime/PKGBUILD
Patches #452 
The path `/opt/rocm/rocclr/include/elf` is not found by `cmake` and has to be added manually.
> [rocm-opencl-runtime] Fix include path

- hip-rocclr/.SRCINFO
- hip-rocclr/PKGBUILD
- hip-rocclr/disable-git-versioning.patch
For the new version to compile, I had to disable precompiled headers. Otherwise, `cmake` fails after a while with `file not found` errors. Furthermore, I removed the option for `cmake` to generate a verbose version string if `git` is available. This addresses #448.
> Hip rocclr 3.9.0

- rocm-validation-suite/.SRCINFO
- rocm-validation-suite/PKGBUILD
- rocm-validation-suite/action.patch
Patch described here: https://github.com/rocm-arch/rocm-arch/issues/64#issuecomment-720572802
It compiles but doesn't really work and more importantly compile every test.
It seems like the string variable in question is just for printing the installed packages into a system, so I replaced it with a arch-specific command.
> Patched pacman-specific solution for action command_string

- rocm-clang-ocl/.SRCINFO
- rocm-clang-ocl/PKGBUILD
I installed all of rocm today, and this was one of the modules that did not build.
I fixed the bitcode directory path to the correct location.
I am on Manjaro, so I don't know if there are differences on other Arch systems.
> Fix bitcode directory path

- rocm-gdb/.SRCINFO
- rocm-gdb/PKGBUILD
Updating rocm-gdb to version 3.9.0 to fix issues with incompatible headers between both dependencies, closes #469.
> [rocm-gdb] Update PKGBUILD to 3.9.0 to match rocm-dbgapi dependency

- hip-rocclr/.SRCINFO
- hip-rocclr/PKGBUILD
Resolves #468
When calling `hipcc` (only a `perl` around `clang` from `llvm-amdgpu`), `clang` looks for the HIP runtime. As an indicator whether it is installed, it uses the (hidden) file `.hipVersion` which is installed by `cmake` to `/opt/rocm/hip/bin` (This is also where it is located in the debian package). The search path however is relative to `clang` (as far as I understood by inspecting the source code), so the `.hipVersion` file needs to be put in `/opt/rocm/bin`.
> [hip-rocclr] Link hipVersion file to /opt/rocm/bin

- llvm-amdgpu/.SRCINFO
- llvm-amdgpu/PKGBUILD
I also replaced `make` with `ninja` in compliance with upstream and the arch `llvm` package. This reduces the compilation time from 50 min. to 33 min on my machine.
> [llvm-amdgpu] Update to 3.10.0

- hipsparse/.SRCINFO
- hipsparse/PKGBUILD
`rocminfo` is already a dependency of `hip-rocclr`, so we can remove from the list of `makedepends`
> [hipsparse] Update to 3.10.0

- miopen-hip/.SRCINFO
- miopen-hip/PKGBUILD
Package does not compile at the moment, see https://github.com/ROCmSoftwarePlatform/MIOpen/issues/658
> [miopen-hip] Update to 4.0.0

- miopen-hip/.SRCINFO
- miopen-hip/PKGBUILD
- Change compiled from `hcc` to rocm's `clang++` as per the MIOpen build
instructions,
- Add `BOOST_CONTAINER_DISABLE_NOINLINE` to fix an issue with `noinline` not
being defined,
- Remove `HALF_ENABLE_F16C_INTRINSICS` as it should be automatically set (as per
http://half.sourceforge.net/half_8hpp.html#a9f8c77eb299462e092d2df4d2d2b7abf),
- Remove `MIOPEN_HIP_COMPILER` as it is automatically determined by CMake based
on `CMAKE_INSTALL_PREFIX`,
- Remove `Boost_NO_BOOST_CMAKE` flag as it does not seem to do anything
Note that although this fixes #511, the issue described in #509 remains.
> [miopen-hip] Boost noinline fix

- rocm-dev/.SRCINFO
- rocm-dev/PKGBUILD
- rocm-libs/.SRCINFO
- rocm-libs/PKGBUILD
- rocm-utils/.SRCINFO
- rocm-utils/PKGBUILD
tensorflow-rocm 2.4.0 looks for these files to know which rocm version it builds against.
These files are contained in the upstream rocm-dev, rocm-utils and rocm-libs RPMs for RHEL/CentOS 8:
https://repo.radeon.com/rocm/centos8/4.0/
> Add version files for rocm-dev, rocm-utils and rocm-libs

- llvm-amdgpu/PKGBUILD
When tensorflow is installed, the CMake script tries to locates `/usr/lib/libtensorflow.so`, and if found enables some additional components of LLVM.  Unfortunately, it assumes that the Tensorflow headers are located in `/usr/include`, but they are in fact installed in `/usr/include/tensorflow`.
This PR also moves the call to CMake into prepare instead of build.
Let me know if you wish to also update the release.
This fixes #572.
> Fix tensorflow include

- llvm-amdgpu/PKGBUILD
In previous commit, I quickly fixed a hard-coded Python 3.9 version to automatically detect it; except I forgot to changes the string to use double quotes.
I should've seen that, but it was such a trivial fix replace `3.9` with `${_pythonver}` that I didn't think twice.
As before, as this is such a minor fixup in the PKGBUILD and does not change the produced package, I did not bother bumping `pkgrel`.
> [llvm-amdgpu] Fix quotes

- rccl/.SRCINFO
- rccl/PKGBUILD
Adding gmock to the build deps for rccl fixes the following error I got when building from a clean chroot (guessing this is the error #593 is complaining about)
```
CMake Error at /usr/lib64/cmake/GTest/GTestTargets.cmake:112 (message):
The imported target "GTest::gmock" references the file
"/usr/lib/libgmock.so.1.10.0"
but this file does not exist.  Possible reasons include:
...
```
\+ update rccl release version
> [rccl] add gmock dep and release 4.1.0

- rocm-core/.SRCINFO
- rocm-core/PKGBUILD
fix rocm_version.h path to match upstream/deb package
This is actually needed for building `python-pytorch-rocm` correctly.
> upgpkg: rocm-core 5.0.1-1

- hip-runtime-amd/PKGBUILD
- hipcub/PKGBUILD
- hipfft/PKGBUILD
- rccl/PKGBUILD
- rocalution/PKGBUILD
- rocblas/PKGBUILD
- rocfft/PKGBUILD
- rocrand/PKGBUILD
- rocsolver/PKGBUILD
- rocsparse/PKGBUILD
- rocthrust/PKGBUILD
This PR adds the additional line `-DAMDGPU_TARGETS=${AMDGPU_TARGETS}` to each of the cmake commands to enable specifying the target to compile for using an environment variable, and otherwise defaults to compiling all targets. This saves a significant amount of time and binary size for people compiling on their own machines, since they can now only compile for their particular GPU target.
Resolves #641
> Fix #641: Use environment variables to specify which gfx targets to compile

- README.md
Just some readme cleanup.
I have also decided to recommend paru over yay. As paru now has devtool capabilities, i.e. you can build AUR packages into chroots directly with paru, (`paru -Syu --chroot`). See: https://www.reddit.com/r/archlinux/comments/tkeuy5/using_paru_u_chroot_to_build_a_pkgbuild_in_a/
Eventually, we may want to point users to using the paru chroot functionality as well in the readme. Or maybe the links to building in chroot should have that information.
> clean up linewidth, rec paru, update links

- rocm-llvm/.SRCINFO
- rocm-llvm/PKGBUILD
manually disable building with lto for rocm-llvm
resolves builds with downstream packages, such as rocm-device-libs
> upgpkg: rocm-llvm 5.0.2-3

- rocm-core/.SRCINFO
- rocm-core/CMakeLists.txt
- rocm-core/PKGBUILD
- rocm-core/rocm_version.c
I just want to note that [the upstream `.deb` release](https://repo.radeon.com/rocm/apt/5.1/pool/main/r/rocm-core/rocm-core_5.1.0.50100-36_amd64.deb) also has a more complex `rocm_version.h` and also include `librocm-core.so`.  Perhaps we should look to be similar?
> upgpkg: rocm-core 5.1.0-1

- rocm-validation-suite/.SRCINFO
- rocm-validation-suite/PKGBUILD
Remove a patch which has been included in this version.
patches #64
> upgpkg: rocm-validation-suite 5.1.0-1

- hip-runtime-nvidia/.SRCINFO
- hip-runtime-nvidia/PKGBUILD
add missing links, use cmake_args format, CMAKE_HIP_ARCH... deprecated
> upgpkg hip-runtime-nvidia 5.1.1-1

- miopen-hip/.SRCINFO
- miopen-hip/PKGBUILD
- miopen-opencl/.SRCINFO
- miopen-opencl/PKGBUILD
- rocm-llvm-mlir/.SRCINFO
- rocm-llvm-mlir/PKGBUILD
There a few notable changes here:
- Instead of building Boost, the system versions are being used. This has become   possible since boostorg/config#393 which is included in Boost 1.78. The fix   relies in `HIP_VERSION` being defined which unfortunately is not always the case (and I am as yet unsure why). As a temporary workaround, the nine   problematic files are manually patched with a `#include <hip/hip_version.h>`. This is not an issue with the OpenCL version.
- I have similarly built against the system version of Half and SQLite. It appears there are no issues due to this.
- I have also tried removing the dependency `ROCmSoftwarePlatform/llvm-project-mlir` and everything compiles fine. I am unsure whether other ROCm packages provide what is necessary or not.
- I have been encountering …
> upgpkg: miopen-hip/opencl 5.1.0-1

- mivisionx/.SRCINFO
- mivisionx/PKGBUILD
MIVisionX does not yet work with FFMpeg 5.0; however FFMpeg 4.4 is available from the Arch repositories (it is a dependency for Firefox, OpenCV, VLC, Blender, among other).
Fixes: #429
Fixes: #597
Patches: #677
> upgpkg: mivisionx 5.1.0-1

- rocm-gdb/PKGBUILD
previous link redirects to the gitlab home page
> fix arch gdb link

- rocm-llvm-mlir/.SRCINFO
- rocm-llvm-mlir/PKGBUILD
* Update checksum
* Patch for correctly appending rpath in cmake file
patches #818
> Update rocm-llvm-mlir to 5.2.0

- hip-runtime-amd/.SRCINFO
- hip-runtime-amd/PKGBUILD
use upstream patch for noinline
update patch for #782
> upgpkg: hip-runtime-amd 5.2.0-4

- rocm-core/.SRCINFO
- rocm-core/PKGBUILD
So rocm-core installs /opt/rocm/include/rocm_version.h which gives a deprecation warning and includes ``rocm-core/rocm_version.h``, this is not installed by the package. This header is used by pytorch, which is how I found the issue.
This change installs the missing header from the .deb
> Also install rocm-core/rocm_version.h

- hsa-amd-aqlprofile-bin/.SRCINFO
- hsa-amd-aqlprofile-bin/PKGBUILD
- rocm-core/.SRCINFO
- rocm-core/PKGBUILD
- rocm-hip-runtime/.SRCINFO
- rocm-hip-runtime/PKGBUILD
Updates for following `PKGBUILDS` (+`.SCRINFO`)
* hsa-amd-aqlprofile-bin -> 5.3.0-1
* rocm-core -> 5.3.0-1
* rocm-hip-runtime -> 5.3.0-1
> Update: hsa-amd-aqlprofile-bin, rocm-core, rocm-hip-runtime

- hsa-amd-aqlprofile-bin/.SRCINFO
- hsa-amd-aqlprofile-bin/PKGBUILD
- rocm-core/.SRCINFO
- rocm-core/PKGBUILD
- rocm-hip-runtime/.SRCINFO
- rocm-hip-runtime/PKGBUILD
This is a bigger update for hsa-amd-aqlprofile, because it's prior structure was just very different and confusing to work with. Now it's based on the structure of rocm-core, so easier to update. For rocm-hip-runtime it was also a update, but a much smaller. Should work out for both of them. They do build and they do work for me.
**Update: rocm-core**
* rocm-core 5.3.2-1
* Update checksum
* Set link to new debian package
**Update: hsa-amd-aqlprofile-bin**
* hsa-amd-aqlprofile 5.3.2-1
* Update checksum
* Streamline pkgbuild structure, based on rocm-core
**Update: rocm-hip-runtime**
* rocm-hip-runtime 5.3.2-1
* Update checksum
* Set link to new debian package
* Streamline pkgbuild structure, based on rocm-core
> Updates for rocm-core, hsa-amd-aqlprofile-bin and rocm-hip-runtime

- hsa-amd-aqlprofile-bin/.SRCINFO
- hsa-amd-aqlprofile-bin/PKGBUILD
- rocm-core/.SRCINFO
- rocm-core/PKGBUILD
- rocm-hip-runtime/.SRCINFO
- rocm-hip-runtime/PKGBUILD
This is a minor package update without additional changes to the PKGBUILDs.
**Update: rocm-hip-runtime**
* rocm-hip-runtime 5.3.3
* Update checksum
* Set link to new debian package
**Update: hsa-amd-aqlprofile-bin**
* hsa-amd-aqlprofile 5.3.3
* Update checksum
* Set link to new debian package
**Update: rocm-core**
* rocm-core 5.3.3
* Update checksum
* Set link to new debian package
> Updates for rocm-core, hsa-amd-aqlprofile-bin and rocm-hip-runtime (5.3.3)

- rocwmma/.SRCINFO
- rocwmma/PKGBUILD
This PR updates rocWMMA to version 6.3.2 (matching the ROCm packages now in extra-testing).
> Update rocWMMA to 6.3.2
