- hsakmt-roct-git/.SRCINFO
- hsakmt-roct-git/PKGBUILD
> Add hsakmt-roct-git replacing roct-thunk-interface-git

- hsa-ext-rocr/.SRCINFO
- hsa-ext-rocr/PKGBUILD
update out-dated `hsa-ext-rocr` version to 3.3.0
solve #30
> Updated hsa-ext-rocr to 3.3.0

- llvm-roc/.SRCINFO
- llvm-roc/PKGBUILD
- Fix URL to point to correct repository
- Add z3 dependency as recommended upstream
- Use dynamic directory name to avoid hardcoded paths
- Add cmake flags from extra/llvm
- Add cmake flags recommended upstream
- Add check after build
> Update llvm-roc to v3.3.0

- rocm-device-libs/.SRCINFO
- rocm-device-libs/PKGBUILD
- rocm-opencl-runtime/.SRCINFO
- rocm-opencl-runtime/PKGBUILD
This is a follow up of #73 but one change at a time
> Split rocm-device-libs from rocm-opencl-runtime

- rock-dkms/.SRCINFO
- rock-dkms/Makefile.patch
- rock-dkms/PKGBUILD
* Bump to 3.3.19
* Add makefile patch to get it build with linux-lts package (currently kernel 5.4)
> [rock-dkms] FEATURE: Bump to 3.3.19 and fix build with linux-lts

- hip-hcc/.SRCINFO
- hip-hcc/PKGBUILD
- hipblas/.SRCINFO
- hipblas/PKGBUILD
- hipcub/.SRCINFO
- hipcub/PKGBUILD
- hipsparse/.SRCINFO
- hipsparse/PKGBUILD
- rocalution/.SRCINFO
- rocalution/PKGBUILD
- rocblas/.SRCINFO
- rocblas/PKGBUILD
- rocm-dev/.SRCINFO
- rocm-dev/PKGBUILD
- rocm-opencl-runtime/.SRCINFO
- rocm-opencl-runtime/PKGBUILD
- rocprim/.SRCINFO
- rocprim/PKGBUILD
- rocthrust/.SRCINFO
- rocthrust/PKGBUILD
@ranisalt can u take a quick look and do the sync as well?
Note: there was quite a few things I could have fixed like getting rid of the version deps and bumping the pkgver's but I just wanted to focus on replacing rocm-comgr in this PR. Don't want to redo some of the work in #119 although a rebase will have to happen on that PR.
> replace rocm-comgr with comgr

- rocm-device-libs/.SRCINFO
- rocm-device-libs/PKGBUILD
Hi,
This worked in my case.
Pablo.
> [rocm-device-libs] Replacing llvm-roc with llvm-amdgpu

- hip-hcc/.SRCINFO
- hip-hcc/PKGBUILD
> [hip-hcc] overrided __hcc_workweek__ when building hip-hcc

- rocsparse/.SRCINFO
- rocsparse/PKGBUILD
Update URL, fix dependencies, tidy-up build() and package() routines.
> [rocsparse] Successful build in clean chroot

- rocalution/.SRCINFO
- rocalution/PKGBUILD
Update URL, license, dependencies and build() and package() routines.
> [rocalution] Successful build in clean chroot

- hipblas/.SRCINFO
- hipblas/PKGBUILD
Update dependencies, build() and package() functions.
> [hipblas] Successful build in clean chroot

- rocclr/.SRCINFO
- rocclr/PKGBUILD
In preparation for the new `hip` package without `hcc`.
> [rocclr] New package

- rocprofiler/.SRCINFO
- rocprofiler/PKGBUILD
- rocprofiler/add_string_header.patch
The patch fixes a build error reported upstream: https://github.com/ROCm-Developer-Tools/rocprofiler/issues/25
> [rocprofiler] Update to 3.5.0

- rocthrust/.SRCINFO
- rocthrust/PKGBUILD
Addresses the build error in #168
> [rocthrust] Fix checksums

- rocalution/.SRCINFO
- rocalution/PKGBUILD
Resolves #212 
Needs #249 to build in a clean chroot.
> [rocalution] Update to 3.5.0

- rocsolver/.SRCINFO
- rocsolver/PKGBUILD
Resolves #233 
To successfully build in a clean chroot #249 is needed.
> [rocsolver] Update to 3.5.0

- rocm-clang-ocl/.SRCINFO
- rocm-clang-ocl/PKGBUILD
- rocm-clang-ocl/remove_hcc_path.patch
> [rocm-clang-ocl] Successful build in clean chroot

- hipsparse/.SRCINFO
- hipsparse/PKGBUILD
Fixes #283 and resolves https://github.com/rocm-arch/rocm-arch/issues/178#issuecomment-650700659
> [hipsparse] Add missing slash in install prefix

- rccl/.SRCINFO
- rccl/PKGBUILD
> [rccl] Compile with hipcc, install license

- hsa-ext-rocr/.SRCINFO
- hsa-ext-rocr/PKGBUILD
> [hsa-ext-rocr] fix 404 on deb file

- llvm-amdgpu-git/.SRCINFO
- llvm-amdgpu-git/PKGBUILD
This package is helpful for investigating build errors like #302 or #303
> [llvm-amdgpu-git] Git version of LLVM backend

- rocblas/.SRCINFO
- rocblas/PKGBUILD
> [rocblas] Disable TensileHost and set COV to 3

- rocclr/.SRCINFO
- rocclr/PKGBUILD
> [rocclr] Remove $srcdir from cmake config file

- roctracer/.SRCINFO
- roctracer/PKGBUILD
> [roctracer] Update to 3.7.0

- rocblas/.SRCINFO
- rocblas/PKGBUILD
> [rocblas] Update to 3.7.0

- rocsolver/.SRCINFO
- rocsolver/PKGBUILD
> [rocsolver] Update to 3.7.0

- hipblas/.SRCINFO
- hipblas/PKGBUILD
> [hipblas] Update to 3.7.0

- rocalution/.SRCINFO
- rocalution/PKGBUILD
> [rocalution] Update to 3.7.0

- rocm-debug-agent/.SRCINFO
- rocm-debug-agent/PKGBUILD
Resolves #345
Builds in a clean chroot.
> [rocm-debug-agent] Update to 3.7.0

- rocm-dbgapi/.SRCINFO
- rocm-dbgapi/PKGBUILD
> [rocm-dbgapi] Remove doxygen documentation

- rocblas/.SRCINFO
- rocblas/PKGBUILD
patches #410, fixes #411, patches #412
> [rocblas] Build Tensile with clang from llvm-amdgpu and enable host libraries

- hip-rocclr/.SRCINFO
- hip-rocclr/PKGBUILD
- hip-rocclr/amdgpu-targets.patch
> [hip-rocclr] Add gfx803 to build targets

- llvm-amdgpu-git/.SRCINFO
- llvm-amdgpu-git/PKGBUILD
> [llvm-amdgpu-git] Remove stray THREADS variable (#418)

- comgr/.SRCINFO
- comgr/PKGBUILD
> [comgr] Update to 3.8.0

- rocblas/.SRCINFO
- rocblas/PKGBUILD
> [rocblas] Update to 3.8.0

- rocsolver/.SRCINFO
- rocsolver/PKGBUILD
> [rocsolver] Update to 3.8.0

- hipblas/.SRCINFO
- hipblas/PKGBUILD
> [hipblas] Update to 3.8.0

- hipsparse/.SRCINFO
- hipsparse/PKGBUILD
> [hipsparse] Update to 3.8.0

- rocalution/.SRCINFO
- rocalution/PKGBUILD
> [rocalution] Add rocrand to depends

- rocm-cmake/.SRCINFO
- rocm-cmake/PKGBUILD
> [rocm-cmake] Update 4.0.0 sha256

- rocm-gdb/.SRCINFO
- rocm-gdb/PKGBUILD
> [rocm-gdb] Update checksum

- rocalution/.SRCINFO
- rocalution/PKGBUILD
Rocalution checksum verification fails. Just fixed this.
> Fix rocalution checksum

- miopen-opencl/.SRCINFO
- miopen-opencl/PKGBUILD
Updated miopen-opencl to 4.0.0 and stop at same error as in #511
> [miopen-opencl] Bump to 4.0.0 and build similar to miopen-hip

- rock-dkms-bin/.SRCINFO
- rock-dkms-bin/PKGBUILD
- rock-dkms-firmware-bin/.SRCINFO
- rock-dkms-firmware-bin/PKGBUILD
This is just a version bump with updated sha256sums.
> [rock-dkms-{firmware-}bin] Version bump for firmware packages.

- llvm-amdgpu/.SRCINFO
- llvm-amdgpu/PKGBUILD
> [llvm-amdgpu] fix compatibility with GCC 11

- miopengemm/.SRCINFO
- miopengemm/PKGBUILD
> [miopengemm] fix build with GCC 11

- rocsolver/.SRCINFO
- rocsolver/PKGBUILD
> upgpkg: rocsolver 5.0.1-1

- README.md
had the wrong links in the previous commit
> update doc links

- rocm-llvm/PKGBUILD
patches #613 
edit: haven't updated pkgrel as don't want to cause an unnecessary rebuild
edit: may want to update the README with this information once this gets merged.
> use NINJAFLAGS from env

- hsakmt-roct/.SRCINFO
- hsakmt-roct/PKGBUILD
> upgpkg hsakmt-roct 5.0.2-2

- rocm-smi-lib/.SRCINFO
- rocm-smi-lib/PKGBUILD
> upgpkg rocm-smi-lib 5.1.0-1

- atmi/.SRCINFO
- atmi/PKGBUILD
> upgpkg: atmi 5.1.0-1

- roctracer/.SRCINFO
- roctracer/PKGBUILD
Signed-off-by: JP-Ellis <josh@jpellis.me>
> upgpkg: roctracer 5.1.0-1

- rocprofiler/.SRCINFO
- rocprofiler/PKGBUILD
> add hsa-rocr to makedep

- hip-runtime-nvidia/.SRCINFO
- hip-runtime-nvidia/PKGBUILD
had the wrong patch in #714 this properly patches #718
> fix search for nvcc

- rocm-opencl-runtime/.SRCINFO
- rocm-opencl-runtime/PKGBUILD
- rocm-opencl-runtime/enable-gfx800.patch
Hello,
As discussed in #741, this should have minimum impact outside of enabling gfx800 cards again.
I'm open to any change done by me or you of course.
Thank you!
> [rocm-opencl-runtime] Enable support for gfx800

- rocminfo/.SRCINFO
- rocminfo/PKGBUILD
> fix enumerator if kfd path does not exist

- hip-runtime-amd/.SRCINFO
- hip-runtime-amd/PKGBUILD
> fix build if no archs found

- rocm-llvm-mlir/PKGBUILD
> [rocm-llvm-mlir] disable LTO

- mivisionx/.SRCINFO
- mivisionx/PKGBUILD
See https://github.com/rocm-arch/rocm-arch/issues/759#issuecomment-1094332729
> [mivisionx] disable LTO

- rocsolver/.SRCINFO
- rocsolver/PKGBUILD
> Fix rocSolver patch checksum

- rocblas/.SRCINFO
- rocblas/PKGBUILD
> upgpkg: rocblas 5.1.1-2

- hipblas/.SRCINFO
- hipblas/PKGBUILD
- update pkgver
- update checksum
- add upstream patch to fix #800
> upgpkg: hipblas 5.2.0-1

- rocsparse/.SRCINFO
- rocsparse/PKGBUILD
add patch to fix gfx1010 compilation
patches #791
> upgpkg: rocsparse 5.2.0-2

- rocm-validation-suite/.SRCINFO
- rocm-validation-suite/PKGBUILD
> upgpkg: rocm-validation-suite 5.2.0-1

- miopen-hip/.SRCINFO
- miopen-hip/PKGBUILD
- update pkgver
- update checksums
- add patch for <rocblas/rocblas.h> build error
- update .SRCINFO
> upgpkg: miopen-hip 5.2.0-1

- migraphx/.SRCINFO
- migraphx/PKGBUILD
Add patch for finding msgpack cmake module
patches #953
> upgpkg: migraphx 5.4.3-1

- README.md
AMD doc URL for package list was updated
> Update package doc URL
